---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`arvoles["height"].quantil(0.95)` é o mesmo que `arvoles["height"].max()`'
  checked: false
- value: '`arvoles["height"].quantil(1)` é o mesmo que `arvoles["height"].min()`'
  checked: false
- value: '`arvoles["height"].quantil(0)` é o mesmo que `arvoles["height"].min()`'
  checked: true
- value: '`arvoles["height"].quantil(0.75)` é o mesmo que `arvoles["height"].median()`'
  checked: false
- value: '`arvoles["height"].quantil(1)` é o mesmo que `arvoles["height"].max()`'
  checked: true
- value: '`arvoles["height"].quantil(0.5)` é o mesmo que `arvoles["height"].median()`'
  checked: true
name: Tudo en-caixa
