---
locale: pt
tags: []
layout: input_bottom
editor: free_form
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices: []
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: arboles\s*\[\s*('altura'|"altura")\s*\]\.median(\s*)
name: Sempre no meio
