---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`min(arboles["altura_tot"])`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`min([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`sum(arboles["diametro"])`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`sum([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`mean(arboles["inclinacion"])`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`mean([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: false
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_output_includes
  output: 'NameError: name ''mean'' is not defined'
name: "¿Disponible sólo en series?"
