---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`1`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`8`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`1` y `8`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`0`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`-1`"
  checked: false
name: A la moda
